// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "C:/Users/madro/OneDrive/Documents/.py/Python-/ProySubA/sk.atm.data.release/draw_SK_IH.C";

#endif
